"""
src/lmgpa/state_manager.py

State Space Definitions for the LMGPA Engine.

This module formalizes the semantic domains described in Section 3.1 of the paper
and defines the system state x_t used in the Stochastic State Machine (Section 3.3).

Mappings to Paper Notation:
- TraceSpec         -> S_tr (Behavioral Specification)
- LogicalSpec       -> S_lg (Logical Specification)
- Artifact          -> (p, pi) (Program + Proof pair)
- VerificationResult-> Output of V (Oracle)
- SynthesisState    -> x_t (Current State = s, p, pi, h)
"""

from dataclasses import dataclass, field, asdict
from enum import Enum, auto
from typing import List, Optional, Dict, Any
import json

class Status(Enum):
    """
    The output domain of the Verification Oracle V.
    Corresponds to { ok, Err_lg, Err_tool } in Section 3.3.
    """
    OK = auto()        # Success (Top)
    ERR_LG = auto()    # Logical Error -> Triggers Refinement (S_lg violation)
    ERR_TOOL = auto()  # Tooling Error -> Triggers Backoff (Timeout, Crash)
    UNKNOWN = auto()   # Initial state

@dataclass
class TraceSpec:
    """
    S_tr: Behavioral Specification.
    Defined by high-level predicates over execution traces.
    """
    name: str
    intent: str  # Original Natural Language Intent (I)
    predicates: List[str]  # e.g., ["Mono(trace)", "Live(trace)"]
    
    # Metadata for the Embedding Function (mu)
    domain_tags: List[str] = field(default_factory=list) # e.g., ["concurrency", "stream"]

@dataclass
class LogicalSpec:
    """
    S_lg: Logical Specification.
    The rigid verification obligation generated by the Embedding Function (mu).
    """
    theorem_name: str
    lean_code: str  # The full Lean 4 theorem statement
    imports: List[str] = field(default_factory=list)
    
    def __repr__(self):
        return f"<LogicalSpec: {self.theorem_name}>"

@dataclass
class Artifact:
    """
    (p, pi): The Candidate Pair.
    Represents a specific point in the Program x Proof space.
    """
    program_code: str  # p (e.g., Python/Rust)
    proof_script: str  # pi (Lean 4 tactic script)
    
    # Auxiliary fields for FFI and compilation
    language: str = "python" 
    dependencies: List[str] = field(default_factory=list)

@dataclass
class VerificationResult:
    """
    The feedback signal from the Verification Oracle V(S_lg, p, pi).
    Used to compute the Semantic Potential Phi(x) and drive the next transition.
    """
    status: Status
    summary: str
    
    # Structured Feedback for the Synthesizer Agent (Context for K_theta)
    feedback: str  # e.g., "Counter-example trace: [Read(0), Write(1)]"
    
    # Raw output for debugging/logging
    raw_stdout: str = ""
    raw_stderr: str = ""
    
    # Phi(x): The distance to correctness
    unsolved_goals_count: int = 0 

@dataclass
class SynthesisState:
    """
    x_t: The Global System State at time t.
    x_t = (S_tr, S_lg, (p, pi)_current, History)
    """
    trace_spec: TraceSpec
    logical_spec: LogicalSpec
    
    # Current Candidate (Can be None at t=0)
    current_artifact: Optional[Artifact] = None
    
    # History h: Sequence of past attempts and feedback
    # List of dicts: { "step": int, "artifact": Artifact, "result": VerificationResult }
    history: List[Dict[str, Any]] = field(default_factory=list)
    
    def to_json(self) -> str:
        """Serializes the state for logging analysis."""
        return json.dumps(asdict(self), default=str, indent=2)

    @property
    def step_count(self) -> int:
        return len(self.history)